CREATE DATABASE IF NOT EXISTS student_integration;
USE student_integration;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    tipo ENUM('admin', 'facilitador', 'user') DEFAULT 'user',
    isBanned BOOLEAN DEFAULT FALSE,
    address VARCHAR(255) DEFAULT NULL,
    profileImg VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 